### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by christhekeele** [jtmoulia/neotomex#14]
I'm consistently getting:
```
(SyntaxError) lib/neotomex/peg.ex:151: unexpected comma. Parentheses are required to solve ambiguity inside containers.
```
on `mix compile` for all recent versions of elixir (`1.1.x`, `1.2.x`), cleaning between runs.

**Comment by niahoo** [comment]
You can use `{:neotomex, github: "jtmoulia/neotomex"}` in your deps. @jtmoulia could you publish a new version to solve this ?

Thanks !

**Comment by jtmoulia** [comment]
Sorry for the wait, but version `0.1.5` has been published to hex and should include the latest fixes.

Let me know if there are any further problems!
