### ISSUE TITLE
AST

### ISSUE THREAD

**Issue by triptec** [jtmoulia/neotomex#15]
Hello, is it possible to parse a string and just get the ast without having had it transformed so one can change it and then send it to the transformer?

**Comment by jtmoulia** [comment]
That's a great idea -- unless you want to give it a go, I'll play with implementing it next week.

**Comment by jtmoulia** [comment]
Hey @triptec -- there's a slightly convoluted for you to accomplish what you want:

For some `My.Grammar` using `Neotomex.ExGrammar` and a custom transform function `my_transform` you might do:

```elixir
parsed = My.Grammar.grammar
  |> Neotomex.Grammar.match("string to parse")
  |> my_transform
  |> Neotomex.Grammar.transform_match
```

Moving forward, we could wrap the `match` function for the `ExGrammar` allowing something like the following -- what do you think?

```elixir
parsed = "string to parse"
  |> My.Grammar.match
  |> my_transform
  |> Neotomex.Grammar.transform_match
```

**Comment by triptec** [comment]
Ok, I'll have to look in to this next week. Thanks for taking the time

**Comment by jtmoulia** [comment]
I'm going to mark this as closed since I have no current plans to implement and their are instructions for hacking around it above.
