### ISSUE TITLE
String.split_at can not split "\r\n" , maybe Regex.split

### ISSUE THREAD

**Issue by cdliyi** [jtmoulia/neotomex#19]
Hey,I'm using neotomex to build a parser and I like it.
I found some issue at line 325 of grammar.ex:

{^match, rest} = String.split_at(input, String.length(match))

```
iex(1)> match = "\r"
"\r"
iex(2)> input = "\r\n"
"\r\n"
iex(3)> String.split_at(input, String.length(match))
{"\r\n", ""}
iex(4)>
```

I think using Regex.split maybe a good choice：

["",^match,rest] = Regex.split(~r/^#{match}/, input, include_captures: true)

```
iex(1)> match = "\r"
"\r"
iex(2)> input = "\r\n"
"\r\n"
iex(3)> Regex.split(~r/^#{match}/, input, include_captures: true)
["", "\r", "\n"]
iex(4)>
```

**Comment by jtmoulia** [comment]
Thank you for the feedback @cdliyi -- interesting issue! To repeat what you're saying It looks like  cause is that `\r\n` is actually a single UTF-8 character, and so unsplittable.

It would alternatively be possible to use `String.codepoints` to get the UTF-8 codepoints as a list, it looks like you would be able to split that. However, with the list to binary conversions I'm not sure if it'd be any faster than the regex solution you described (which makes sense to me!)

Would you be interested in submitting the fix as a PR?
